### PR TITLE
WIP Retexture

### PR DESCRIPTION
**Pull request by Bluberry-Kat**
hi again. o/ 
thought you'd appreciate some pretty art. i only have wooden crates right now, here's what they look like.

accepting feedback. will post updates as they develop.

### CODE REVIEW

**Comment by Draylar** [comment]
Wow, those look beyond fantastic. It seems my pixel art ego has been obliterated yet again.

**Comment by Birgliss** [comment]
The Iron Crate took me a lot longer than I wanted :sweat_smile: 


I went a darker route, mostly just because the Cauldron palette is easier to work with than the Iron Block palette. 
Did you know the Iron Block palette has 8 different shades of grey, and they're _all boring?_

The reason this took so long is because I wanted to make it Diamond Plate.
Yeah, you try drawing this pattern at 16x16 resolution and making it look good. It's not easy.
image

More updates soon. Hopefully quicker this time.

**Comment by Draylar** [comment]
Iron Crates looking fantastic as well! I have also been the culprit of the Iron Block palette in the past. Using the Cauldron as an alternative is a great idea.

**Comment by Birgliss** [comment]
Burnout is really tough and I dunno when I'll next be able to make progress on this.  
In the meantime you're welcome to merge this and use the textures that already exist.  
There's no real reason this should be a release blocker. I can just make another PR if I get more done.

**Comment by Bluberry-Kat** [comment]
Recovered from burnout some, not sure if this gold crate texture is any good, but I made it and that's what counts ;p  
Maybe you could add a red mushroom to the loot table :thinking:

**Comment by Draylar** [comment]
Finally getting around to merging this... apologies for the super long delay, and thanks again for your wonderful texture contributions. Can't wait to use these in-game!

**Pull request merged**
